name: common_module_flutter_example
description: Sample app to handle version control and rating for OSAM applications
publish_to: 'none'
version: 3.0.0+20220127

environment:
  sdk: ">=2.12.0"


dependencies:
  flutter:
    sdk: flutter
  common_module_flutter:
    path: ../
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.6
  group_radio_button: ^1.1.0
  flutter_fgbg: ^0.2.0
  firebase_crashlytics: ^2.4.5
  firebase_analytics: ^9.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

#for firebase remote config



flutter:
  uses-material-design: true