name: common_module_flutter_example
description: Sample app to handle version control and rating for OSAM applications
publish_to: 'none'
version: 3.0.2+20251029

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'


dependencies:
  flutter:
    sdk: flutter
  osam_common_module_flutter:
    path: ../
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.0.5
  group_radio_button: ^1.3.0
  flutter_fgbg: ^0.6.0
  firebase_crashlytics: ^4.1.5
  firebase_analytics: ^11.3.5
  firebase_performance: ^0.10.0+10
  firebase_core: ^3.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

#for firebase remote config



flutter:
  uses-material-design: true