name: common_module_flutter_example
description: Sample app to handle version control and rating for OSAM applications
publish_to: 'none'
version: 3.0.1+20230417

environment:
  sdk: ">=2.12.0"


dependencies:
  flutter:
    sdk: flutter
  common_module_flutter:
    path: ../
  cupertino_icons: ^1.0.5
  shared_preferences: ^2.1.0
  group_radio_button: ^1.3.0
  flutter_fgbg: ^0.2.2
  firebase_crashlytics: ^3.1.0
  firebase_analytics: ^10.2.0
  firebase_performance: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

#for firebase remote config



flutter:
  uses-material-design: true