name: Build

on:
  push:
    branches: [main]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    name: Build and test
    runs-on: macos-latest

    steps:
    - name: Configure enviroment
      uses: actions/checkout@v3
    - name: Check broken links
      uses: JustinBeckwith/linkinator-action@v1
      with:
        paths: "**/*.md"
        linksToSkip: "https://developer.android.com/build/multidex"
    - uses: kuhnroyal/flutter-fvm-config-action@v2
      id: fvm-config-action
      with:
        path: '.fvmrc'
    - name: Download flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
        cache: true
        cache-key: 'flutter-:os:-:version:'
        cache-path: '${{ runner.tool_cache }}/flutter/:os:-:version:'
    - name: Install dependencies
      run: flutter pub get
    - name: Format code
      run: dart format --set-exit-if-changed .
    - name: Analyze static code
      run: flutter analyze
    - name: Check publish warnings
      run: dart pub publish --dry-run

  # Disabled until unblock release process
  # deployment:
  #   if: ${{ github.ref_type == 'tag' }}
  #   needs: build
  #   name: Deploy package
  #   permissions:
  #     id-token: write
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: dart-lang/setup-dart@v1
  #     - uses: kuhnroyal/flutter-fvm-config-action@v1
  #     - name: Download flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: ${{ env.FLUTTER_VERSION }}
  #         cache: true
  #         cache-key: 'flutter-:os:-:version:'
  #         cache-path: '${{ runner.tool_cache }}/flutter/:os:-:version:'
  #     - name: Publish package
  #       run: dart pub publish -v -f